filebeat.inputs:
- type: filestream
  id: default-filestream
  paths:
    - /var/lib/docker/containers/*/*.log
    - /var/log/pods:/var/log/pods:ro
    - /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v2.task/k8s.io:/var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v2.task/k8s.io:ro

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_docker_metadata: ~

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: true
  ssl.certificate_authorities: "certs/ca/ca.crt"
